### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by zoubir-remila** [juampi92/auto-updater#10]
hello, 
i hav added autouploader to my app, but i hav just the only message :

You have a clone of the repository. Use 'git pull' to be up-to-date

in app.js : i have add the example from doc

var autoupdater = new AutoUpdater({
    pathToJson: 'package.json',
    autoupdate: true,
    checkgit: true,
    jsonhost: 'https://github.com/amazighezed/amazing-auto-updater/blob/master/package.json',
    contenthost: 'https://github.com/amazighezed/amazing-auto-updater/archive/master.zip',
    progressDebounce: 0,
    devmode: true
});

package.json :

"auto-updater":{
    "repo":"https://github.com/amazighezed/amazing-auto-updater",
    "branch":"master"
  },

**Comment by juampi92** [comment]
Check the documentation. When it says "host", is just that, the host, not the full URL. The auto-updater will figure out the full url. If you leave them empty, it'll still work.

And if you are in development mode, this will not work, cause there's a .git project folder. You should use 'git pull' to fetch the last changes, not this plugin that will mess up your git project.

**Comment by juampi92** [comment]
Read the package.json config [here](https://github.com/juampi92/auto-updater#packagejson-configuration), and the example of use [here](https://github.com/juampi92/auto-updater#example). You are not following the instructions

**Comment by zoubir-remila** [comment]
i have run build for mac and i launch my app with this parameters and i have this error
<img width="413" alt="capture d ecran 2017-01-13 a 16 53 19" src="https://cloud.githubusercontent.com/assets/17833664/21936246/cbdb08a6-d9b0-11e6-8104-8962096fe93a.png">

**Comment by juampi92** [comment]
Dude, you don't even have it as a dependency on your [package.json](https://github.com/amazighezed/amazing-auto-updater/blob/master/package.json)... Are you for real?

**Comment by zoubir-remila** [comment]
my json now is : 
{
  "name": "amazing-auto-updater",
  "version": "3.0.0",
  "auto-updater": {
    "repo": "/amazighezed/amazing-auto-updater",
    "branch": "master"
  },
  "description": "mise a jour",
  "main": "app.js",
  "dependencies": {
    "auto-updater": "^1.0.2",
    "electron": "^1.4.14",
    "electron-plugins": "^0.1.0",
    "electron-updater": "^0.3.1"
  },
  "devDependencies": {
    "electron-packager": "^8.5.0"
  },
  "scripts": {
    "start": "node_modules/.bin/electron .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "electron-packager . MyApp"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/amazighezed/amazing-auto-updater"
  },
  "author": "zoubir remila",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/amazighezed/amazing-auto-updater/issues"
  },
  "homepage": "https://github.com/amazighezed/amazing-auto-updater"
}


in my app.js 👍 
var AutoUpdater = require('auto-updater');
var autoupdater = new AutoUpdater({
    pathToJson: '',
    autoupdate: true,
    checkgit: true,
    jsonhost: '',
    contenthost: '',
    progressDebounce: 0,
    devmode: true
});

in github i have version 5.0.0
in local app i have 3.0.0 
<img width="386" alt="capture d ecran 2017-01-16 a 11 15 40" src="https://cloud.githubusercontent.com/assets/17833664/21978928/226a7a34-dbdd-11e6-9893-1cf6d2f7d00a.png">

thank you
