### ISSUE TITLE
Can't find package.json with Electron 4.1.2 on Windows

### ISSUE THREAD

**Issue by evo-nxst** [juampi92/auto-updater#11]
I locally fixed with module "app-root-path" in **auto-updater.js**

`appRoot = require('app-root-path');
var loadClientJson = function() {
   var jsonPath = appRoot+"/package.json",
   ...`
But still...

**Comment by juampi92** [comment]
mmm, error log? 
Use the `pathToJson `config instead. Internally it does: 
`path.join('.', this.attrs.pathToJson, 'package.json');`

**Comment by evo-nxst** [comment]
The script looks for the file in this folder. **Error: ENOENT: no such file or directory, open 'E:\Cloud\G-Drive\Web development\Node JS Projects\Terabyte Service\build\rswma-app-win32-x64\package.json'**

package.json is here: **E:\Cloud\G-Drive\Web development\Node JS Projects\Terabyte Service\build\rswma-app-win32-x64\resources\app\package.json**

And not only package.json, as it is impossible to download archives because they do not find the application root directory

**Comment by juampi92** [comment]
@N3stY then you should set the `pathToJson `attribute to `'resources\app'`

**Comment by evo-nxst** [comment]
This is not the solution, `'resources\apps'` exists only in the compiled version. In the the repository, this folders do not exist, since it is the source code

**Comment by juampi92** [comment]
You do realize that this package is for replacing your local project files with the remote github files? This does not compile anything.. You'll have to do that yourself... A "if dev use this folder, and if prod, use this other folder and then, when done (check events fired), compile it or whatever". 
I'm not gonna tell you how to do your software...
